spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379

jwt:
 secret:
    key: 7LWc7KSA7JiB7J6F64uI64ukLuy1nOykgOyYgeyeheuLiOuLpC4=
---
spring:
  config:
    activate:
      on-profile: local

  mail:
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    host: smtp.naver.com
    port: 465
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl: # 네이버는 ssl 필수
          enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/card
    password: ENC(ioXO2hzfipQL4WEM3EAYn5L+RuyuVUdk)

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: true

cloud:
  aws:
    s3:
      bucket: "${bucketName}"
    region:
      static: ap-northeast-2
    credentials:
      access-key: "${AccessKey}"
      secret-key: "${SecretKey}"

---
spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:~/todolist
    driver-class-name: org.h2.Driver
    username: sa
    password:

  mail:
    username: test@test.com
    password: test
    host: test.test.test
    port: 1111
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl: # 네이버는 ssl 필수
          enable: true

cloud:
  aws:
    s3:
      bucket: test
    region:
      static: test
    credentials:
      access-key: test
      secret-key: test