spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none

jwt:
 secret:
    key: 7LWc7KSA7JiB7J6F64uI64ukLuy1nOykgOyYgeyeheuLiOuLpC4=
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(A1bFPjzEREj3HNOrHJ4aAA==)
    url: ENC(czUHDXLPgAmxJ3O/dC2xmBvKZ/dDxqUimr5Yl2gTbWVjmpkfv6Hxil0pM15/c7r2)
    password: ENC(GI1jpFnyG73kkoZdYLV6YWbVBVBqU6pY)

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:~/todolist
    driver-class-name: org.h2.Driver
    username: sa
    password: