spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ENC(TsoSYxjLr+XDjuk7jKB8Dg==)
#    url: ENC(hTJTixW0O564LP55OZAZfLOs6UvOWhV59NX7DAWPn0s+tauToFA7SkxqHHLo8OOt)
#    password: ekqls832@@
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
